baseURL: "https://mjvo.github.io/course-stub"
title: "Course #"

defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1

MetaDataFormat: "yaml"

theme: 
  - "hugo-course"

FootnoteReturnLinkContents: "↩"

outputFormats:
  Remark:
    baseName: index
    mediaType: text/html
    isHTML: true

params:
  course:
    name: "Course Name"
    dept_url: "https://aahvs.duke.edu"
    dept_logo: "http://placehold.it/284x56&text=DEPT+LOGO"
    day_time: "Days of Week, hh:mm - hh:mm AM/PM"
    location: "Room #, Building"
    hero_img: "http://placehold.it/1920x1080&text=Hero+Image"
    hero_img_credit: "Image: <a href=\"#\">Title</a> by <a href=\"#\">Author Name</a>, YEAR"